#!/bin/bash
TARGET=`pwd`/gnome-shell/gnome-shell.css

# Load ruby gems if neceesary
if [[ ! $PATH == *ruby* ]] && type ruby >/dev/null 2>&1; then
  export PATH=$PATH:$(ruby -rubygems -e "puts Gem.user_dir")/bin
  echo $PATH
fi

# Determine, if the arch version of theme should be compiled
if [ $(uname -r | rev | cut -d '-' -f 1 | rev) == 'ARCH' ] || \
  ([ ! -z $1 ] && [ $1 == 'arch' ]);
then
  SOURCE=`pwd`/gnome-shell/gnome-shell-arch.scss
else
  SOURCE=`pwd`/gnome-shell/gnome-shell.scss
fi

# Compile or watch
if [ ! -z $1 ] && [ $1 == 'watch' ]; then
  sass --watch $SOURCE:$TARGET
else
  sass $SOURCE $TARGET
fi
