#!/bin/bash
TARGET=`pwd`/gnome-shell/gnome-shell.css

# Load ruby gems if neceesary
if [[ ! $PATH == *ruby* ]] && type ruby >/dev/null 2>&1; then
  export PATH=$PATH:$(ruby -rubygems -e "puts Gem.user_dir")/bin
  echo $PATH
fi

# Determine, if the arch version of theme should be compiled
if [ -z $1 ] || [ $1 == 'watch' ]; then
  # Auto-determine version
  if [ $(uname -r | rev | cut -d '-' -f 1 | rev) == 'ARCH' ]; then
    version='arch'
  else
    version='default'
  fi
else
  version=$1
fi


if [ $version == 'arch' ]; then
  SOURCE=`pwd`/gnome-shell/gnome-shell-arch.scss
else
  SOURCE=`pwd`/gnome-shell/gnome-shell.scss
fi

# Compile or watch
if [ ! -z $1 ] && [ $1 == 'watch' ]; then
  find . -name \*.scss | entr ./compile reload
elif [ ! -z $1 ] && [ $1 == 'reload' ]; then
  sass $SOURCE $TARGET
  gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval 'Main.loadTheme();'
else
  sass $SOURCE $TARGET
fi
