#!/bin/bash
version=1.3.0
mkdir -p out
./compile default
zip -r out/gnome-shell-deimos-$version.zip . -x .git**\* .gitignore **\*.sass-cache**\* screenshots**\* out**\*
./compile arch
zip -r out/gnome-shell-deimos-$version-arch.zip . -x .git**\* .gitignore **\*.sass-cache**\* screenshots**\* out**\*
